checking for full run

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -120,65 +120,69 @@ jobs:
     # We need additional `&& ! cancelled()` to have the job being able to cancel
     if: ${{ success() || failure() || ( always() && ! cancelled() ) }}
     steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{ runner.temp }}/style_check
-          ROBOT_CLICKHOUSE_SSH_KEY<<RCSK
-          ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
-          RCSK
-          EOF
-      - name: Download changed images
-        # even if artifact does not exist, e.g. on `do not test` label or failed Docker job
-        continue-on-error: true
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ env.TEMP_PATH }}
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-      - name: Style Check
-        run: |
-          cd "$GITHUB_WORKSPACE/tests/ci"
-          python3 style_check.py
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
+      - name: test
+        run: echo "test"    
+      # - name: Set envs
+      #   run: |
+      #     cat >> "$GITHUB_ENV" << 'EOF'
+      #     TEMP_PATH=${{ runner.temp }}/style_check
+      #     ROBOT_CLICKHOUSE_SSH_KEY<<RCSK
+      #     ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
+      #     RCSK
+      #     EOF
+      # - name: Download changed images
+      #   # even if artifact does not exist, e.g. on `do not test` label or failed Docker job
+      #   continue-on-error: true
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: changed_images
+      #     path: ${{ env.TEMP_PATH }}
+      # - name: Check out repository code
+      #   uses: ClickHouse/checkout@v1
+      #   with:
+      #     clear-repository: true
+      # - name: Style Check
+      #   run: |
+      #     cd "$GITHUB_WORKSPACE/tests/ci"
+      #     python3 style_check.py
+      # - name: Cleanup
+      #   if: always()
+      #   run: |
+      #     docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+      #     docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+      #     sudo rm -fr "$TEMP_PATH"
   FastTest:
     needs: DockerHubPush
     runs-on: [self-hosted, builder]
     steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/fasttest
-          REPO_COPY=${{runner.temp}}/fasttest/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          EOF
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ env.TEMP_PATH }}
-      - name: Fast Test
-        run: |
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 fast_test_check.py
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
+      - name: test
+        run: echo "test"
+      # - name: Set envs
+      #   run: |
+      #     cat >> "$GITHUB_ENV" << 'EOF'
+      #     TEMP_PATH=${{runner.temp}}/fasttest
+      #     REPO_COPY=${{runner.temp}}/fasttest/ClickHouse
+      #     CACHES_PATH=${{runner.temp}}/../ccaches
+      #     EOF
+      # - name: Check out repository code
+      #   uses: ClickHouse/checkout@v1
+      #   with:
+      #     clear-repository: true
+      # - name: Download changed images
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: changed_images
+      #     path: ${{ env.TEMP_PATH }}
+      # - name: Fast Test
+      #   run: |
+      #     cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+      #     cd "$REPO_COPY/tests/ci" && python3 fast_test_check.py
+      # - name: Cleanup
+      #   if: always()
+      #   run: |
+      #     docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+      #     docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+      #     sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
 ##   CompatibilityCheckX86:
 #     needs: [BuilderDebRelease]
 #     runs-on: [self-hosted, style-checker]
