checking for BuilderBinClangTidy

diff --git a/.github/workflows/pull_tests.yml b/.github/workflows/pull_tests.yml
--- a/.github/workflows/pull_tests.yml
+++ b/.github/workflows/pull_tests.yml
@@ -1,4 +1,4 @@
-name: PullTestCI
+name: PullclangCI
 
 env:
   # Force the stdout and stderr streams to be unbuffered
@@ -82,7 +82,7 @@ jobs:
         with:
           name: changed_images
           path: ${{ runner.temp }}/changed_images.json
-  BuilderBinDarwin:
+  BuilderBinClangTidy:
     needs: [DockerHubPush]
     runs-on: [self-hosted, builder]
     steps:
@@ -93,7 +93,7 @@ jobs:
           IMAGES_PATH=${{runner.temp}}/images_path
           REPO_COPY=${{runner.temp}}/build_check/ClickHouse
           CACHES_PATH=${{runner.temp}}/../ccaches
-          BUILD_NAME=binary_darwin
+          BUILD_NAME=binary_tidy
           EOF
       - name: Download changed images
         uses: actions/download-artifact@v3
@@ -123,144 +123,185 @@ jobs:
           docker ps --quiet | xargs --no-run-if-empty docker kill ||:
           docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
           sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
-  BuilderBinDarwinAarch64:
-    needs: [DockerHubPush]
-    runs-on: [self-hosted, builder]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/build_check
-          IMAGES_PATH=${{runner.temp}}/images_path
-          REPO_COPY=${{runner.temp}}/build_check/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          BUILD_NAME=binary_darwin_aarch64
-          EOF
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ env.IMAGES_PATH }}
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-          submodules: true
-      - name: Build
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
-      - name: Upload build URLs to artifacts
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BUILD_URLS }}
-          path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"                   
-  BuilderDebRelease:
-    needs: [DockerHubPush]
-    runs-on: [self-hosted, builder]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/build_check
-          IMAGES_PATH=${{runner.temp}}/images_path
-          REPO_COPY=${{runner.temp}}/build_check/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          BUILD_NAME=package_release
-          EOF
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ env.IMAGES_PATH }}
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-          fetch-depth: 0  # for performance artifact
-          submodules: true
-      - name: Build
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
-      - name: Upload build URLs to artifacts
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BUILD_URLS }}
-          path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
-  BuilderDebAarch64:
-    needs: [DockerHubPush]
-    runs-on: [self-hosted, test-only]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/build_check
-          IMAGES_PATH=${{runner.temp}}/images_path
-          REPO_COPY=${{runner.temp}}/build_check/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          BUILD_NAME=package_aarch64
-          EOF
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ runner.temp }}/images_path
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-          submodules: true
-          fetch-depth: 0  # for performance artifact
-      - name: Build
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
-      - name: Upload build URLs to artifacts
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BUILD_URLS }}
-          path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
-  MarkReleaseReady:
-    needs:
-      - BuilderBinDarwin
-      - BuilderBinDarwinAarch64
-      - BuilderDebRelease
-      - BuilderDebAarch64
-    runs-on: [self-hosted, builder]
-    steps:
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-      - name: Mark Commit Release Ready
-        run: |
-          cd "$GITHUB_WORKSPACE/tests/ci"
-          python3 mark_release_ready.py          
+  # BuilderBinDarwin:
+  #   needs: [DockerHubPush]
+  #   runs-on: [self-hosted, builder]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=binary_darwin
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ env.IMAGES_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         submodules: true
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"                  
+  # BuilderBinDarwinAarch64:
+  #   needs: [DockerHubPush]
+  #   runs-on: [self-hosted, builder]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=binary_darwin_aarch64
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ env.IMAGES_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         submodules: true
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"                   
+  # BuilderDebRelease:
+  #   needs: [DockerHubPush]
+  #   runs-on: [self-hosted, builder]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=package_release
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ env.IMAGES_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         fetch-depth: 0  # for performance artifact
+  #         submodules: true
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH"
+  # BuilderDebAarch64:
+  #   needs: [DockerHubPush]
+  #   runs-on: [self-hosted, test-only]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=package_aarch64
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ runner.temp }}/images_path
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         submodules: true
+  #         fetch-depth: 0  # for performance artifact
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
+  # MarkReleaseReady:
+  #   needs:
+  #     - BuilderBinDarwin
+  #     - BuilderBinDarwinAarch64
+  #     - BuilderDebRelease
+  #     - BuilderDebAarch64
+  #   runs-on: [self-hosted, builder]
+  #   steps:
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #     - name: Mark Commit Release Ready
+  #       run: |
+  #         cd "$GITHUB_WORKSPACE/tests/ci"
+  #         python3 mark_release_ready.py          
