checking for style check

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -113,41 +113,41 @@ jobs:
         with:
           name: changed_images
           path: ${{ runner.temp }}/changed_images.json
-  # StyleCheck:
-  #   needs: DockerHubPush
-  #   runs-on: [self-hosted, style-checker]
-  #   # We need additional `&& ! cancelled()` to have the job being able to cancel
-  #   if: ${{ success() || failure() || ( always() && ! cancelled() ) }}
-  #   steps:
-  #     - name: Set envs
-  #       run: |
-  #         cat >> "$GITHUB_ENV" << 'EOF'
-  #         TEMP_PATH=${{ runner.temp }}/style_check
-  #         ROBOT_CLICKHOUSE_SSH_KEY<<RCSK
-  #         ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
-  #         RCSK
-  #         EOF
-  #     - name: Download changed images
-  #       # even if artifact does not exist, e.g. on `do not test` label or failed Docker job
-  #       continue-on-error: true
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: changed_images
-  #         path: ${{ env.TEMP_PATH }}
-  #     - name: Check out repository code
-  #       uses: ClickHouse/checkout@v1
-  #       with:
-  #         clear-repository: true
-  #     - name: Style Check
-  #       run: |
-  #         cd "$GITHUB_WORKSPACE/tests/ci"
-  #         python3 style_check.py
-  #     - name: Cleanup
-  #       if: always()
-  #       run: |
-  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-  #         sudo rm -fr "$TEMP_PATH"
+  StyleCheck:
+    needs: DockerHubPush
+    runs-on: [self-hosted, style-checker]
+    # We need additional `&& ! cancelled()` to have the job being able to cancel
+    if: ${{ success() || failure() || ( always() && ! cancelled() ) }}
+    steps:
+      - name: Set envs
+        run: |
+          cat >> "$GITHUB_ENV" << 'EOF'
+          TEMP_PATH=${{ runner.temp }}/style_check
+          ROBOT_CLICKHOUSE_SSH_KEY<<RCSK
+          ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
+          RCSK
+          EOF
+      - name: Download changed images
+        # even if artifact does not exist, e.g. on `do not test` label or failed Docker job
+        continue-on-error: true
+        uses: actions/download-artifact@v3
+        with:
+          name: changed_images
+          path: ${{ env.TEMP_PATH }}
+      - name: Check out repository code
+        uses: ClickHouse/checkout@v1
+        with:
+          clear-repository: true
+      - name: Style Check
+        run: |
+          cd "$GITHUB_WORKSPACE/tests/ci"
+          python3 style_check.py
+      - name: Cleanup
+        if: always()
+        run: |
+          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+          sudo rm -fr "$TEMP_PATH"
   # FastTest:
   #   needs: DockerHubPush
   #   runs-on: [self-hosted, style-checker]
@@ -243,49 +243,49 @@ jobs:
 # #########################################################################################
 # #################################### ORDINARY BUILDS ####################################
 # #########################################################################################
-  BuilderDebRelease:
-    # needs: [DockerHubPush, FastTest, StyleCheck]
-    needs: [DockerHubPush]    
-    runs-on: [self-hosted]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/build_check
-          IMAGES_PATH=${{runner.temp}}/images_path
-          REPO_COPY=${{runner.temp}}/build_check/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          BUILD_NAME=package_release
-          EOF
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ env.IMAGES_PATH }}
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-          fetch-depth: 0  # for performance artifact
-          submodules: true
-      - name: Build
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
-      - name: Upload build URLs to artifacts
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BUILD_URLS }}
-          path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
+  # BuilderDebRelease:
+  #   # needs: [DockerHubPush, FastTest, StyleCheck]
+  #   needs: [DockerHubPush]    
+  #   runs-on: [self-hosted]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=package_release
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ env.IMAGES_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         fetch-depth: 0  # for performance artifact
+  #         submodules: true
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH"
 #   BuilderBinRelease:
 #     needs: [DockerHubPush, FastTest, StyleCheck]
 #     runs-on: [self-hosted, builder]
@@ -327,49 +327,49 @@ jobs:
 #           docker ps --quiet | xargs --no-run-if-empty docker kill ||:
 #           docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
 #           sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
-  BuilderDebAarch64:
-    # needs: [DockerHubPush, FastTest, StyleCheck]
-    needs: [DockerHubPush]    
-    runs-on: [self-hosted]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/build_check
-          IMAGES_PATH=${{runner.temp}}/images_path
-          REPO_COPY=${{runner.temp}}/build_check/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          BUILD_NAME=package_aarch64
-          EOF
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ runner.temp }}/images_path
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-          submodules: true
-          fetch-depth: 0  # for performance artifact
-      - name: Build
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
-      - name: Upload build URLs to artifacts
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BUILD_URLS }}
-          path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
+  # BuilderDebAarch64:
+  #   # needs: [DockerHubPush, FastTest, StyleCheck]
+  #   needs: [DockerHubPush]    
+  #   runs-on: [self-hosted]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=package_aarch64
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ runner.temp }}/images_path
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         submodules: true
+  #         fetch-depth: 0  # for performance artifact
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
 #   BuilderDebAsan:
 #     needs: [DockerHubPush, FastTest, StyleCheck]
 #     runs-on: [self-hosted, builder]
@@ -626,47 +626,47 @@ jobs:
 #           docker ps --quiet | xargs --no-run-if-empty docker kill ||:
 #           docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
 #           sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
-#   BuilderBinDarwin:
-#     needs: [DockerHubPush, FastTest, StyleCheck]
-#     runs-on: [self-hosted, builder]
-#     steps:
-#       - name: Set envs
-#         run: |
-#           cat >> "$GITHUB_ENV" << 'EOF'
-#           TEMP_PATH=${{runner.temp}}/build_check
-#           IMAGES_PATH=${{runner.temp}}/images_path
-#           REPO_COPY=${{runner.temp}}/build_check/ClickHouse
-#           CACHES_PATH=${{runner.temp}}/../ccaches
-#           BUILD_NAME=binary_darwin
-#           EOF
-#       - name: Download changed images
-#         uses: actions/download-artifact@v3
-#         with:
-#           name: changed_images
-#           path: ${{ env.IMAGES_PATH }}
-#       - name: Check out repository code
-#         uses: ClickHouse/checkout@v1
-#         with:
-#           clear-repository: true
-#           submodules: true
-#       - name: Build
-#         run: |
-#           sudo rm -fr "$TEMP_PATH"
-#           mkdir -p "$TEMP_PATH"
-#           cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-#           cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
-#       - name: Upload build URLs to artifacts
-#         if: ${{ success() || failure() }}
-#         uses: actions/upload-artifact@v3
-#         with:
-#           name: ${{ env.BUILD_URLS }}
-#           path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
-#       - name: Cleanup
-#         if: always()
-#         run: |
-#           docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-#           docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-#           sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
+  # BuilderBinDarwin:
+  #   needs: [DockerHubPush, FastTest, StyleCheck]
+  #   runs-on: [self-hosted, builder]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=binary_darwin
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ env.IMAGES_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         submodules: true
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
 #   BuilderBinAarch64:
 #     needs: [DockerHubPush, FastTest, StyleCheck]
 #     runs-on: [self-hosted, builder]
