build image for rpm deb

diff --git a/.github/workflows/pull_test.yaml b/.github/workflows/pull_test.yaml
--- a/.github/workflows/pull_test.yaml
+++ b/.github/workflows/pull_test.yaml
@@ -6,9 +6,23 @@ env:
 
 on:  # yamllint disable-line rule:truthy
   push:
+  # pull_request:
+  #   types:
+  #     - synchronize
+  #     - reopened
+  #     - opened
+  #   branches:
+  #     - master
+  #   paths-ignore:
+  #     - 'CHANGELOG.md'
+  #     - 'README.md'
+  #     - 'SECURITY.md'
+  #     - 'docker/docs/**'
+  #     - 'docs/**'
+  #     - 'utils/check-style/aspell-ignore/**'  
 jobs:
   DockerHubPushAarch64:
-    runs-on: [self-hosted, testing]
+    runs-on: [self-hosted, test-only]
     steps:
       - name: Check out repository code
         uses: ClickHouse/checkout@v1
@@ -24,7 +38,7 @@ jobs:
           name: changed_images_aarch64
           path: ${{ runner.temp }}/docker_images_check/changed_images_aarch64.json
   DockerHubPushAmd64:
-    runs-on: [self-hosted, testing]
+    runs-on: [self-hosted, test-only]
     steps:
       - name: Check out repository code
         uses: ClickHouse/checkout@v1
@@ -41,7 +55,7 @@ jobs:
           path: ${{ runner.temp }}/docker_images_check/changed_images_amd64.json
   DockerHubPush:
     needs: [DockerHubPushAmd64, DockerHubPushAarch64]
-    runs-on: [self-hosted, testing]
+    runs-on: [self-hosted, test-only]
     steps:
       - name: Check out repository code
         uses: ClickHouse/checkout@v1
@@ -66,44 +80,44 @@ jobs:
         with:
           name: changed_images
           path: ${{ runner.temp }}/changed_images.json
-  BuilderBinDarwinAarch64:
-    needs: [DockerHubPush]
-    runs-on: [self-hosted, testing]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/build_check
-          IMAGES_PATH=${{runner.temp}}/images_path
-          REPO_COPY=${{runner.temp}}/build_check/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          BUILD_NAME=binary_darwin_aarch64
-          EOF
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ env.IMAGES_PATH }}
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-          submodules: true
-      - name: Build
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
-      - name: Upload build URLs to artifacts
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BUILD_URLS }}
-          path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
+  # BuilderBinDarwinAarch64:
+  #   needs: [DockerHubPush]
+  #   runs-on: [self-hosted, testing]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/build_check
+  #         IMAGES_PATH=${{runner.temp}}/images_path
+  #         REPO_COPY=${{runner.temp}}/build_check/ClickHouse
+  #         CACHES_PATH=${{runner.temp}}/../ccaches
+  #         BUILD_NAME=binary_darwin_aarch64
+  #         EOF
+  #     - name: Download changed images
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: changed_images
+  #         path: ${{ env.IMAGES_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #         submodules: true
+  #     - name: Build
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci" && python3 build_check.py "$BUILD_NAME"
+  #     - name: Upload build URLs to artifacts
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BUILD_URLS }}
+  #         path: ${{ env.TEMP_PATH }}/${{ env.BUILD_URLS }}.json
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
